const items = [
    {
        id:'001',
        image:'images/mens_shirts/1.jpeg',
        ratings:{
            stars:4.5,
            reviews:1400,
        },
        company:'Levis',
        item_name:'Blend cotton Double-Packet Shirt',
        current_price:600,
        original_price:1050,
        discount:42,
    },
    {
        id:'002',
        image:'images/mens_shirts/2.jpeg',
        ratings:{
            stars:4.5,
            reviews:1400,
        },
        company:'Levis',
        item_name:'Blend cotton Double-Packet Shirt',
        current_price:600,
        original_price:1050,
        discount:42,
    },
    {
        id:'003',
        image:'images/mens_shirts/3.jpeg',
        ratings:{
            stars:4.5,
            reviews:1400,
        },
        company:'Levis',
        item_name:'Blend cotton Double-Packet Shirt',
        current_price:600,
        original_price:1050,
        discount:42,
    },
    {
        id:'004',
        image:'images/mens_shirts/4.jpeg',
        ratings:{
            stars:4.5,
            reviews:1400,
        },
        company:'Levis',
        item_name:'Blend cotton Double-Packet Shirt',
        current_price:600,
        original_price:1050,
        discount:42,
        
    },
    {
        id:'005',
        image:'images/mens_shirts/5.jpeg',
        ratings:{
            stars:4.5,
            reviews:1400,
        },
        company:'Levis',
        item_name:'Blend cotton Double-Packet Shirt',
        current_price:600,
        original_price:1050,
        discount:42,
    },
    {
        id:'006',
        image:'images/mens_shirts/6.jpeg',
        ratings:{
            stars:4.5,
            reviews:1400,
        },
        company:'Levis',
        item_name:'Blend cotton Double-Packet Shirt',
        current_price:600,
        original_price:1050,
        discount:42,
    },
    {
        id:'007',
        image:'images/mens_shirts/7.jpeg',
        ratings:{
            stars:4.5,
            reviews:1400,
        },
        company:'Levis',
        item_name:'Blend cotton Double-Packet Shirt',
        current_price:600,
        original_price:1050,
        discount:42,
    },
    {
        id:'008',
        image:'images/mens_shirts/8.jpeg',
        ratings:{
            stars:4.5,
            reviews:1400,
        },
        company:'Levis',
        item_name:'Blend cotton Double-Packet Shirt',
        current_price:600,
        original_price:1050,
        discount:42,
    },
    {
        id:'009',
        image:'images/mens_shirts/9.jpeg',
        ratings:{
            stars:4.5,
            reviews:1400,
        },
        company:'Levis',
        item_name:'Blend cotton Double-Packet Shirt',
        current_price:600,
        original_price:1050,
        discount:42,
    },

    {
        id:'010',
        image:'images/mens_shirts/10.jpeg',
        ratings:{
            stars:4.5,
            reviews:1400,
        },
        company:'Levis',
        item_name:'Blend cotton Double-Packet Shirt',
        current_price:600,
        original_price:1050,
        discount:42,
    }
];